user:
  email: akash@brightfox.ai
  username: akash
  full_name: Akash
  
vm:
  name: dev-akash-vm-001
  project: gcp-engg-vm
  zone: us-east1-b
  machine_type: n2-standard-2
  disk_size_gb: 50
  image_family: ubuntu-2204-lts
  image_project: ubuntu-os-cloud
  description: "Small VM - Basic development work"

billing:
  account: 016B46-D56B18-B9B11D
