# Ankush's Developer VM Configuration
# Created: 2025-12-03

vm:
  name: dev-ankush-gnome-nm-001
  project_id: gcp-engg-vm
  zone: us-east1-b
  machine_type: n2-standard-4
  disk_size_gb: 100
  static_ip: 35.231.209.38
  image_family: gcp-engg-golden-v3

user:
  username: ankush
  default_password: bfAI2025vmtest!

paths:
  projects: /home/ankush/projects
  logs: /var/log/dev-activity
  backups: /home/ankush/backups

gcs_sync:
  bucket: brightfox-dev-logs
  prefix: ankush
  interval_minutes: 5
