vm:
  project_id: gcp-engg-vm
  zone: us-east1-b
  name: dev-shm-vm-002

users:
  developer:
    username: vm1_gcp_brightfox_ai

paths:
  projects_root: /home/vm1_gcp_brightfox_ai/projects
  activity_log_dir: /var/log/dev-activity
  git_log_dir: /var/log/dev-git
  backups_dir: /var/backups/dev-repos

gcs_sync:
  enabled: true
  bucket: "gs://akash-dev-vm-backups"
