user:
  email: vm1.gcp@brightfox.ai
  username: shm
  full_name: Scott Test (SHM)
  
vm:
  name: dev-shm-vm-001
  project: gcp-engg-vm
  zone: us-east1-b
  machine_type: n2-standard-4
  disk_size_gb: 100
  image_family: ubuntu-2204-lts
  image_project: ubuntu-os-cloud

billing:
  account: 016B46-D56B18-B9B11D
