user:
  email: <email>
  username: <username>
  full_name: <full name>

vm:
  name: <vm-name>
  project: gcp-engg-vm
  zone: us-east1-b
  machine_type: n2-standard-4
  disk_size_gb: 100
  image_family: ubuntu-2204-lts
  image_project: ubuntu-os-cloud

applications:
  chrome: true
  windsurf: true
  jupyter: true
  python: true
  node: true
  git: true
  utils: true
  build_tools: true

billing:
  account: <billing-account-id>
