# Allowed System Packages
# Whitelist of packages that can be installed on developer VMs

apt_packages:
  essential:
    - git
    - curl
    - wget
    - unzip
    - build-essential
    - ca-certificates
    - gnupg
    - lsb-release
    
  python:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    
  nodejs:
    - nodejs
    - npm
    
  utilities:
    - jq
    - htop
    - vim
    - nano
    - tmux
    - screen
    - tree
    - zip
    - rsync
    - net-tools
    
  development:
    - gcc
    - g++
    - make
    - cmake
    - pkg-config
    
  version_control:
    - git-lfs
    
  databases:
    - postgresql-client
    - mysql-client
    - sqlite3
    
  optional:
    - docker.io
    - docker-compose

cloud_sdks:
  - name: gcloud
    description: Google Cloud SDK
    install_url: https://cloud.google.com/sdk/docs/install
    
  - name: gh
    description: GitHub CLI
    install_url: https://github.com/cli/cli/blob/trunk/docs/install_linux.md
    
  - name: az
    description: Azure CLI
    install_url: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux
    
  - name: azd
    description: Azure Developer CLI
    install_url: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd

languages:
  go:
    supported_versions:
      - "1.22"
      - "1.21"
      - "1.20"
    default_version: "1.22"
    install_path: /usr/local/go
    
  rust:
    install_method: rustup
    default_toolchain: stable
